title: AGV München
url: http://agvm.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
language: de
google_analytics_id: null # TODO: provide Google Analytics ID when going online

safe: true
permalink: /aktuelles/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: veranstaltungen
    values:
      layout: event
      allday: false
      start: 1970-01-01 12:29:13+00:00
      end: 1970-01-01 22:29:13+00:00
      venue:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

collections:
  veranstaltungen:
    output: true
    permalink: /veranstaltungen/:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

markdown: kramdown

prose:
  siteurl: "http://agvm.github.io"
  media: images
  relativeLinks: 'http://agvm.github.io/links.jsonp'
  ignore:
    - .gitignore
    - calendar.json
    - CNAME
    - css
    - Gemfile
    - Gemfile.lock
    - links.jsonp
    - README.md
    - robots.txt
    - _config.yml
    - _includes
    - _layouts
    - _sass

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

sass:
  style: :compressed
