title: AGV München
url: http://agvm.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
language: de
google_analytics_id: TODO_REPLACE_ME

safe: true
permalink: /aktuelles/:year/:month/:day/:title

exclude:
  - Gemfile
  - Gemfile.lock

markdown: kramdown

prose:
  siteurl: "http://agvm.github.io"
  media: images
  relativeLinks: 'http://agvm.github.io/links.jsonp'
  ignore:
    - .gitignore
    - _config.yml
    - CNAME
    - Gemfile
    - Gemfile.lock
    - links.jsonp

gems:
  - jekyll-feed
  - jekyll-sitemap
